"""
Output directory management and file organization.

Provides centralized management of the ./vca_output/ directory structure,
ensuring consistent file naming and organized storage of all preprocessing outputs.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Any

from ..exceptions import VideoChapterAutomaterError


class OutputType(Enum):
    """Types of output files generated by preprocessing."""
    VIDEO = "video"
    AUDIO = "audio"
    SCENES = "scenes"
    CHAPTERS = "chapters"
    METADATA = "metadata"
    LOGS = "logs"
    SOURCE = "source"


class OutputManager:
    """
    Manages output directory structure and file organization.

    Creates and maintains a structured output directory with subdirectories
    for different types of preprocessing outputs.

    Directory structure:
        ./vca_output/
        ├── video/           # Re-encoded videos
        ├── audio/           # Extracted audio files
        ├── scenes/          # Scene images
        ├── chapters/        # Chapter marker files
        ├── metadata/        # Processing metadata (JSON, stats)
        └── logs/            # Processing logs
    """

    # Subdirectory mapping
    SUBDIRS = {
        OutputType.VIDEO: "video",
        OutputType.AUDIO: "audio",
        OutputType.SCENES: "scenes",
        OutputType.CHAPTERS: "chapters",
        OutputType.METADATA: "metadata",
        OutputType.LOGS: "logs",
        OutputType.SOURCE: "source",
    }

    def __init__(
        self,
        base_dir: Path = Path("./vca_output"),
        project_name: Optional[str] = None,
        auto_create: bool = True
    ):
        """
        Initialize output manager.

        Args:
            base_dir: Base output directory path
            project_name: Optional project subfolder name
            auto_create: Automatically create directory structure if True
        """
        self.base_dir = base_dir.resolve()
        if project_name:
            self.base_dir = self.base_dir / project_name

        if auto_create:
            self.ensure_structure()

    def ensure_structure(self) -> None:
        """Create output directory structure if it doesn't exist."""
        self.base_dir.mkdir(parents=True, exist_ok=True)

        for output_type in OutputType:
            subdir = self.get_subdir(output_type)
            subdir.mkdir(parents=True, exist_ok=True)

    def get_subdir(self, output_type: OutputType) -> Path:
        """
        Get path to subdirectory for specific output type.

        Args:
            output_type: Type of output

        Returns:
            Path to subdirectory
        """
        subdir_name = self.SUBDIRS[output_type]
        return self.base_dir / subdir_name

    def get_output_path(
        self,
        video_name: str,
        output_type: OutputType,
        extension: str,
        suffix: str = ""
    ) -> Path:
        """
        Generate organized output file path.

        Args:
            video_name: Base name of video file (without extension)
            output_type: Type of output (video, audio, etc.)
            extension: File extension (without leading dot)
            suffix: Optional suffix to add before extension (e.g., "_reencoded")

        Returns:
            Full path to output file
        """
        subdir = self.get_subdir(output_type)

        if suffix:
            filename = f"{video_name}{suffix}.{extension}"
        else:
            filename = f"{video_name}.{extension}"

        return subdir / filename

    def get_scene_subdir(self, video_name: str) -> Path:
        """
        Get subdirectory for scene images from specific video.

        Args:
            video_name: Base name of video file

        Returns:
            Path to video-specific scene subdirectory
        """
        scenes_dir = self.get_subdir(OutputType.SCENES)
        video_scenes_dir = scenes_dir / video_name
        video_scenes_dir.mkdir(parents=True, exist_ok=True)
        return video_scenes_dir

    def generate_manifest(
        self,
        video_name: str,
        outputs: Dict[str, Any],
        stats: Optional[Dict[str, Any]] = None
    ) -> Path:
        """
        Generate JSON manifest of all outputs for a video.

        Args:
            video_name: Base name of video file
            outputs: Dictionary of output paths by type
            stats: Optional processing statistics

        Returns:
            Path to manifest file
        """
        manifest = {
            "video_name": video_name,
            "timestamp": datetime.now().isoformat(),
            "outputs": {
                key: str(value) if isinstance(value, Path) else value
                for key, value in outputs.items()
            },
            "statistics": stats or {}
        }

        manifest_path = self.get_output_path(
            video_name,
            OutputType.METADATA,
            "json",
            suffix="_manifest"
        )

        with open(manifest_path, 'w', encoding='utf-8') as f:
            json.dump(manifest, f, indent=2)

        return manifest_path

    def list_outputs(self, output_type: Optional[OutputType] = None) -> List[Path]:
        """
        List all output files of a specific type.

        Args:
            output_type: Type of outputs to list (None = all types)

        Returns:
            List of output file paths
        """
        if output_type:
            subdir = self.get_subdir(output_type)
            return sorted(subdir.glob("*"))
        else:
            all_outputs = []
            for otype in OutputType:
                all_outputs.extend(self.list_outputs(otype))
            return sorted(all_outputs)

    def cleanup(
        self,
        output_type: Optional[OutputType] = None,
        older_than_days: Optional[int] = None
    ) -> int:
        """
        Clean up output files.

        Args:
            output_type: Type of outputs to clean (None = all)
            older_than_days: Only delete files older than N days (None = all files)

        Returns:
            Number of files deleted
        """
        from datetime import timedelta

        files_deleted = 0
        cutoff_time = None

        if older_than_days is not None:
            cutoff_time = datetime.now() - timedelta(days=older_than_days)

        outputs = self.list_outputs(output_type)

        for output_path in outputs:
            if not output_path.is_file():
                continue

            # Check age if specified
            if cutoff_time:
                file_mtime = datetime.fromtimestamp(output_path.stat().st_mtime)
                if file_mtime > cutoff_time:
                    continue

            try:
                output_path.unlink()
                files_deleted += 1
            except OSError:
                pass

        return files_deleted

    def get_disk_usage(self) -> Dict[str, int]:
        """
        Calculate disk usage for each output type.

        Returns:
            Dictionary mapping output type to size in bytes
        """
        usage = {}

        for output_type in OutputType:
            total_size = 0
            for file_path in self.list_outputs(output_type):
                if file_path.is_file():
                    total_size += file_path.stat().st_size

            usage[output_type.value] = total_size

        return usage

    def validate_output(self, output_path: Path) -> bool:
        """
        Validate that output file exists and is non-empty.

        Args:
            output_path: Path to output file

        Returns:
            True if valid, False otherwise
        """
        if not output_path.exists():
            return False

        if not output_path.is_file():
            return False

        # Check file is not empty
        if output_path.stat().st_size == 0:
            return False

        return True

    def create_readme(self) -> Path:
        """
        Create README file explaining output directory structure.

        Returns:
            Path to README file
        """
        readme_content = """# VideoChapterAutomater Output Directory

This directory contains all outputs from video preprocessing and chapter generation.

## Directory Structure

- **video/**: Re-encoded video files with GPU acceleration
- **audio/**: Extracted audio files (WAV 16kHz mono for transcription)
- **scenes/**: Scene images extracted from videos (organized by video name)
- **chapters/**: Chapter marker files (FFmpeg metadata format)
- **metadata/**: Processing manifests and statistics (JSON format)
- **logs/**: Processing logs and debug information

## File Naming Convention

Files are named according to the pattern:
`{video_name}{suffix}.{extension}`

Example:
- `my_video_reencoded.mp4` - Re-encoded video
- `my_video.wav` - Extracted audio
- `my_video_manifest.json` - Processing metadata

## Scene Images

Scene images are organized in subdirectories:
`scenes/{video_name}/scene_{number}_frame_{index}.png`

Example:
- `scenes/my_video/scene_001_frame_01.png`
- `scenes/my_video/scene_001_frame_02.png`

## Manifest Files

Each processed video gets a manifest JSON file containing:
- Timestamp of processing
- Paths to all generated outputs
- Processing statistics (times, scene counts, etc.)

## Cleanup

To clean up old output files, use the cleanup functionality in the OutputManager
or manually delete files from the respective subdirectories.
"""

        readme_path = self.base_dir / "README.txt"
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)

        return readme_path

    def __repr__(self) -> str:
        return f"OutputManager(base_dir={self.base_dir})"
